services:
  arduinolcd:
    image: arduinolcd
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    group_add:
      - 20 # dialout
    network_mode: host
networks: {}
